mhwd-kernel: fix syntax

diff --git a/scripts/mhwd-kernel b/scripts/mhwd-kernel
--- a/scripts/mhwd-kernel
+++ b/scripts/mhwd-kernel
@@ -12,7 +12,7 @@ fi
 # check usage
 if [ ! "$#" -le 2 ]; then
 
-  >&2 printf 'USAGE: %s [new kernel: linux(version)] [optional - remove the current kernel: rmc]\n' "$0"
+  >&2 printf ' >> USAGE: %s [new kernel: linux(version)] [optional - remove the current kernel: rmc]\n' "$0"
 
   exit 1
 
@@ -30,7 +30,7 @@ REMOVEPKGS=""
 CURRENT="linux$(uname -r | cut -d\. -f1,2 | sed s'/.//2')"
 
 if [ "$(echo "$1" | grep linux)" = "" ]; then
-    printf "ERROR: Did you enter a valid kernel?\n >> USAGE: mhwd-kernel [new kernel: linux(version)] [optional - remove the current kernel: rmc]\n"
+    printf " >> ERROR: Did you enter a valid kernel?\n >> USAGE: mhwd-kernel [new kernel: linux(version)] [optional - remove the current kernel: rmc]\n"
     exit 1
 fi
 
