make mhwd-kernel stop if not updated

diff --git a/scripts/mhwd-kernel b/scripts/mhwd-kernel
--- a/scripts/mhwd-kernel
+++ b/scripts/mhwd-kernel
@@ -39,8 +39,13 @@ if [ "$CURRENT" = "$1" ]; then
     exit 1
 fi
 
+if [ ! -z $(pacman -Qu) ]; then
+    printf "ERROR: Your system is outdated. You have to Update it first!\n"
+    exit 1
+fi
+
 # sync databases
-pacman -Syyu --noconfirm
+pacman -Syy
 
 for PKG in $(pacman -Qq | grep $CURRENT) ; do
     NEWPKG=$(echo $PKG | sed s/$CURRENT/$1/)
@@ -53,7 +58,7 @@ done
 
 
 # Install new packages
-if [ "${ADDPKGS}" != "" ]; then
+if [ ! -z "${ADDPKGS}"]; then
     echo ""
     echo "> Installing new packages"
     pacman -S ${ADDPKGS} --noconfirm
@@ -63,7 +68,7 @@ else
 fi
 
 # Remove all packages
-if [ "${REMOVEPKGS}" != "" ] && [ "$2" == "rmc" ]; then
+if [ ! -z  "${REMOVEPKGS}"] && [ "$2" == "rmc" ]; then
     echo ""
     echo "> Removing packages"
     pacman -Rdd ${REMOVEPKGS} --noconfirm
