created mhwd-fb, added status function to mhwd-gpu and improved mhwd-kernel

diff --git a/scripts/mhwd-kernel b/scripts/mhwd-kernel
--- a/scripts/mhwd-kernel
+++ b/scripts/mhwd-kernel
@@ -1,5 +1,8 @@
 #!/bin/bash
 
+# This script should exit on error
+set -e
+
 # do UID checking here so someone can at least get usage instructions
 if [ "$EUID" != "0" ]; then
     echo "error: This script must be run as root."
@@ -19,6 +22,10 @@ fi
 export LANG=C
 export LC_MESSAGES=C
 
+# variables to hold packages
+ADDPKGS=""
+REMOVEPKGS=""
+
 # sync databases
 pacman -Syy
 
@@ -26,12 +33,28 @@ for PKG in $(pacman -Qq | grep $1) ; do
     NEWPKG=$(echo $PKG | sed s/$1/$2/)
     PKGCHECK=`pacman -Ss "$NEWPKG" | grep "$NEWPKG" | head -1 | cut -d/ -f2 | cut -d' ' -f1`
     if [ "$NEWPKG" == "$PKGCHECK" ] ; then
-       if [ "$3" == "yes" ] ; then
-          pacman -Rdd $PKG --noconfirm
-       fi
-       pacman -S $NEWPKG --noconfirm
+       REMOVEPKGS="${REMOVEPKGS} $PKG"
+       ADDPKGS="${ADDPKGS} $NEWPKG"
     fi
 done
+
+
+# Install new packages
+if [ "${ADDPKGS}" != "" ]; then
+    echo ""
+    echo "> Installing new packages"
+    pacman -S ${ADDPKGS} --noconfirm
+else
+    echo "warning: no packages have been installed! Did you enter a valid kernel?"
+	exit 1
+fi
+
+# Remove all packages
+if [ "${REMOVEPKGS}" != "" ] && [ "$3" == "yes" ]; then
+    echo ""
+    echo "> Removing packages"
+    pacman -Rdd ${REMOVEPKGS} --noconfirm
+fi
 
 
 
